name: Pump it
on: [push]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Pump it up
        uses: actions/checkout@v2
      - name: Let's get it started
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: "latest"
          activate-environment: pumpin
      - name: Pump it louder
        run: |
          conda install -c conda-forge vtk pyvista
      - name: Let's work it out
        run: |
          python test.py
      - name: Pump it up a little more
        uses: actions/upload-artifact@v2
        with:
          name: test-artifact
          path: test.png
